pipeline:
  build:
    image: maven
    commands:
      - mvn clean package
    volumes:
      - m2-repository-cache:/root/.m2/repository

  containerize:
    image: plugins/docker
    repo: hello-spring
    registry: 172.17.0.1:5000
    tags: latest
    insecure: true
