kind: pipeline
name: default

steps:
- name: build
  image: maven
  commands:
  - mvn clean package
  volumes:
  - m2-repository-cache:/root/.m2/repository

- name: containerize
  image: plugins/docker
  repo: hello-spring
  tags: latest
